from curl_cffi import requests                                                                                                                                                                                                                                                                                                                                                                                                                       
from typing import Union, List                                                                                                                                                                                                                                                                                                                                                                                                                       
from util import Util                                                                                                                                                                                                                                                                                                                                                                                                                       

class Session:                                                                                                                                                                                                                                                                                                                                                                                                                       
    @staticmethod                                                                                                                                                                                                                                                                                                                                                                                                                       
    def session() -> List[Union[requests.Session, str, str, str]]:                                                                                                                                                                                                                                                                                                                                                                                                                       
        proxy = Util.get_random_proxy()                                                                                                                                                                                                                                                                                                                                                                                                                       

        browsers = [                                                                                                                                                                                                                                                                                                                                                                                                                       
            ("chrome_133", '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"', "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36")                                                                                                                                                                                                                                                                                                                                                                                                                       
        ]                                                                                                                                                                                                                                                                                                                                                                                                                       

        impersonate, sec_ch_ua, user_agent = browsers[0]                                                                                                                                                                                                                                                                                                                                                                                                                       

        session = requests.Session(impersonate="chrome133a", proxies={"http": proxy, "https": proxy}, default_headers=0, verify=False)                                                                                                                                                                                                                                                                                                                                                                                                                       

        return (session, sec_ch_ua, user_agent, proxy)   